name: test_workflow
on:
  pull_request:
    - branches:
        - main
  workflow_dispatch:
    inputs:
      test:
        type: choice
        description: Test workflow
        options:
          - true
          - false
if : ${{ github.event_name == 'workflow_dispatch' }}
 run-name: testing the new workflow
if: ${{ github.event_name == 'pull_request' }}
 run-name: testing the pull request workflow    
jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ inputs.test == 'true' }}
    steps:
      - name: Test
        run: echo "Test workflow"