name: test_workflow
run-name: ${{ github.event_name }} run ${{ inputs.test }}
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      test:
        type: choice
        description: Test workflow
        options:
          - true
          - false 

jobs:
  test1:
    runs-on: ubuntu-latest
    if: ${{ inputs.test == 'true' }}
    steps:
      - name: Test
        run: echo "Test workflow"
