name: test_workflow
on:
  pull_request:
    - branches:
        - main
  workflow_dispatch:
    inputs:
      test:
        type: choice
        description: Test workflow
        options:
          - true
          - false 

jobs:
  test1:
    runs-on: ubuntu-latest
    if: ${{ inputs.test == 'true' }}
    steps:
      - name: Test
        run: echo "Test workflow"

  test2:
    runs-on: ubuntu-latest
    steps:
      - name: Set run-name for workflow_dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "::set-output name=run-name::testing the new workflow"
      - name: Set run-name for pull_request
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "::set-output name=run-name::testing the pull request workflow"