name: test_workflow
run-name: testing the new workflow

on:
  workflow_dispatch:
  inputs:
    test:
      type: choice
      description: Test workflow
      options:
        - true
        - false
      
jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ inputs.test == 'true' }}
    steps:
      - name: Test
        run: echo "Test workflow"